### ISSUE TITLE
(Jigsaw) End Frame Spacing Issue 

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#20]
![Screen Shot 2018-01-23 at 4:57 PM](http://marker.screenshots.prod.s3.amazonaws.com/6a14127748ae47458c950b2da3a32729-1516726638136.png)

Too much space compared to the psd

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=pineapple](http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=pineapple)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>1260 x 896</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Milosh911** [comment]
Fixed
