### ISSUE TITLE
(Jigsaw) iPad Footer Spacing

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#22]
![Screen Shot 2018-01-23 at 5:17 PM](http://marker.screenshots.prod.s3.amazonaws.com/af1dd677ade9415b8a89398234e0655a-1516727842963.png)

**Summary:** 
When the game is opened in the iPad mode the footer does not sit at the bottom of the screen.

**Steps to Reproduce:** 
Open the game in portrait mode on an iPad (768px in width)

**Expected Results:** 
The footer should sit at the bottom of the screen.

**Actual Results:** 
The footer floats near the middle.

**Notes:**

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=pineapple](http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=pineapple)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>768 x 1024</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by mristic505** [comment]
Solved
