### ISSUE TITLE
(Jigsaw) End 3 frame line-spacing is too tight

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#23]
![Screen Shot 2018-01-23 at 5:40 PM](http://marker.screenshots.prod.s3.amazonaws.com/7f08088466e344a1b2713b6a76c47ac3-1516729220758.png)

**Summary:** 
Fruity Fact line spacing is too tight compared to PSD when the width is between 810px and 1200px.

**Steps to Reproduce:** 
Play the game the game to the last frame and adjust the width to any amount between 810px and 1200px

**Expected Results:** 
Line height should be closer to 'normal' or '16px'

**Actual Results:** 
Line height is 12px and seems to tight.

**Notes:**

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=cranberry](http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=cranberry)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>840 x 896</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Rodolfo-Reynoso** [comment]
#Original Mobile view on psd

![psd-line-space](https://user-images.githubusercontent.com/20693544/35291931-e34f50b0-003c-11e8-9b7c-d92721e04ff0.png)

**Comment by mristic505** [comment]
@Milosh911 

Can you look into this one?

**Comment by Milosh911** [comment]
I have updated line height to "normal" on that breakpoint, but left it on 12px on lower one (<810px), since epsilon (?) complained that text is too close to the edges and suggested that we reduce line height. 
Is that okay?
@mristic505 @Rodolfo-Reynoso

**Comment by Rodolfo-Reynoso** [comment]
@Milosh911 
That's a good point. I think it's fine to leave the `line-height = 12px` for **< 810px** screensizes.
