### ISSUE TITLE
(Pop a Fruit) Excess space between CTA and text

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#25]
![Screen Shot 2018-01-23 at 6:39 PM](http://marker.screenshots.prod.s3.amazonaws.com/42fd755a2e234b6495282034bf6cda16-1516732793730.png)

**Summary:** 
There is more space between the white background and the CTA button than when compared to the PSDs.

**Steps to Reproduce:** 
Play the game to the last frame.

**Expected Results:** 
CTA Buttons should be a bit closer to the white background.

**Actual Results:** 
CTA buttons are a bit farther away.

**Notes:**
Not sure if this is worth a fix. But Epsilon has complained about similar issues.

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=pop-a-fruit&play=apple_rapsberry](http://rodolfo.brandconnections.com/jjflavorsgames/?page=pop-a-fruit&play=apple_rapsberry)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Rodolfo-Reynoso** [comment]
# Original PSD Desktop Image


![pop-a-fruit-cta-spacing](https://user-images.githubusercontent.com/20693544/35294468-9fec51d0-0044-11e8-9e1d-e35dad4915ae.png)

**Comment by Milosh911** [comment]
done
