### ISSUE TITLE
(Pop a Fruit) CTA Spacing is too close to the bottom border

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#28]
![Screen Shot 2018-01-23 at 7:51 PM](http://marker.screenshots.prod.s3.amazonaws.com/b009bf6352c141159d8b14d5644fe5be-1516737105234.png)

**Summary:** 
CTA spacing is too close to the bottom border.

**Steps to Reproduce:** 
Play the game to the end frame with a width > 471px.

**Expected Results:** 
CTA spacing should be closer to the white space.

**Actual Results:** 
CTA spacing is too close to the bottom border.

**Notes:**
Also not sure if this needs to be fixed. But I have seen Epsilon note similar bugs on the pdfs. 

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=pop-a-fruit&play=apple_raspberry](http://rodolfo.brandconnections.com/jjflavorsgames/?page=pop-a-fruit&play=apple_raspberry)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>470 x 896</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Rodolfo-Reynoso** [comment]
# Original PSD image

![pop-a-fruit-cta-spacing-2](https://user-images.githubusercontent.com/20693544/35297479-0d8930fc-004d-11e8-8022-9c45d8222776.png)

**Comment by Milosh911** [comment]
Updated. I had to add a little bit of left padding to play again link, so it can miss boy's leg. The result is that CTA's are in correct place, but "Play again" and "Spin" is not centered. Its not really noticeable, so it should be fine?

**Comment by mristic505** [comment]
Looks good to me
