### ISSUE TITLE
(Hidden Pictures) CTA Spacing needs to be moved up

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#29]
![Screen Shot 2018-01-23 at 8:14 PM](http://marker.screenshots.prod.s3.amazonaws.com/1fa41896054f430b8253db73813a6535-1516738466430.png)

**Summary:** 
Spacing above CTA is a bit too large.

**Steps to Reproduce:** 
Play game to the last frame.

**Expected Results:** 
CTA section should be closer to the white background.

**Actual Results:** 
CTA section is a bit farther than the white background compared to the PSDs.

**Notes:**
This might be overkill. But logging it anyway just in case.

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=hidden-pictures&play=berry](http://rodolfo.brandconnections.com/jjflavorsgames/?page=hidden-pictures&play=berry)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>1354 x 896</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Rodolfo-Reynoso** [comment]
# Original PSD Image
![hidden-pictures-cta-spacing](https://user-images.githubusercontent.com/20693544/35298509-66b81dc0-0050-11e8-86b3-12c39ba7d5a0.png)

**Comment by Milosh911** [comment]
Fixed
