### ISSUE TITLE
(Hidden Pictures) Font-size seems small

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#34]
![Screen Shot 2018-01-25 at 5:12 PM](http://marker.screenshots.prod.s3.amazonaws.com/844d9bd62ff2473d9c343c09202499e5-1516900360863.png)

**Summary:** 
The font-size seems too small.

**Steps to Reproduce:** 
Go to the last frame of the game. Change the width to between 470px and 600px.

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=hidden-pictures&play=berry](http://rodolfo.brandconnections.com/jjflavorsgames/?page=hidden-pictures&play=berry)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>471 x 874</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1058</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Milosh911** [comment]
Yep, originally it was larger but I matched it to the game I was supposed to use as reference: http://rodolfo.brandconnections.com/jjflavorsgames/?page=matching-numbers&play=passion-dragonfruit

Its 10px in both games. Please advise on what should I do, increase font size, or leave it as it is @Rodolfo-Reynoso ?

**Comment by Rodolfo-Reynoso** [comment]
@Milosh911 Leave as is, thanks!
